#!/bin/bash

: ${1?"Usage: $0 argument"}

brightness=`cat /sys/class/backlight/intel_backlight/brightness`
max_brightness=`cat /sys/class/backlight/intel_backlight/max_brightness`
new_brightness=`printf %.0f $(echo "$brightness*$1" | bc -l)`

if [ $new_brightness -gt $max_brightness ] 
then
    new_brightness=$max_brightness
fi

echo $new_brightness > /sys/class/backlight/intel_backlight/brightness
